name: Ontop - Challenge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Download and install Chrome
      run: |
        curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb > chrome.deb
        sudo dpkg -i chrome.deb
        sudo apt-get install -f
        chrome --version
    
    - name: Build with Maven
      run: mvn -B clean test
